'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class admincalendar

    '''<summary>
    '''Head1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''DisplayingLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DisplayingLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''AllButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AllButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''OpenButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OpenButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ClientSiteLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClientSiteLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ClientSiteDDL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClientSiteDDL As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''EmployeeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EmployeeLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EmployeeDDL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EmployeeDDL As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''StartDateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StartDateLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''StartDateTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StartDateTB As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DaysLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DaysLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DaysDDL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DaysDDL As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''CellHeightLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CellHeightLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CellHeightDDL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CellHeightDDL As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''CreateShift_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CreateShift_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''DayPilotCalendar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DayPilotCalendar As Global.DayPilot.Web.Ui.DayPilotCalendar

    '''<summary>
    '''ShiftModalLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShiftModalLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ShiftInstance_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShiftInstance_ID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ShiftInstance_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShiftInstance_Name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ShiftInstance_EmployeeDDL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShiftInstance_EmployeeDDL As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ShiftInstance_ShiftNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShiftInstance_ShiftNotes As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ShiftInstance_PayRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShiftInstance_PayRate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ShiftInstance_OnDutyMealPeriods control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShiftInstance_OnDutyMealPeriods As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ShiftInstance_StartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShiftInstance_StartDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ShiftInstance_StartTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShiftInstance_StartTime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ShiftInstance_EndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShiftInstance_EndDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ShiftInstance_EndTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShiftInstance_EndTime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DeleteShift_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DeleteShift_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''UpdateShift_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdateShift_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Shift_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Shift_ID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Client_ID_ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Client_ID_ As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ClientSite_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClientSite_ID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Pre_SI_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pre_SI_Name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Pre_SI_Notes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pre_SI_Notes As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Pre_SI_startdatetime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pre_SI_startdatetime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Pre_SI_enddatetime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pre_SI_enddatetime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Pre_SI_username control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pre_SI_username As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Pre_ST_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pre_ST_Name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Pre_ST_Description control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pre_ST_Description As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Pre_ST_employee_id control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pre_ST_employee_id As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Pre_ST_startdatetime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pre_ST_startdatetime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Pre_ST_enddatetime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pre_ST_enddatetime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Pre_ST_ondutymeals control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pre_ST_ondutymeals As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Pre_ST_startday control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pre_ST_startday As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Pre_ST_endday control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pre_ST_endday As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Pre_ST_username control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pre_ST_username As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ShiftTemplate_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShiftTemplate_Name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ShiftTemplate_EmployeeDDL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShiftTemplate_EmployeeDDL As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ShiftTemplate_ShiftDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShiftTemplate_ShiftDescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ShiftTemplate_PayRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShiftTemplate_PayRate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ShiftTemplate_OnDutyMealPeriods control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShiftTemplate_OnDutyMealPeriods As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ShiftTemplate_StartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShiftTemplate_StartDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ShiftTemplate_EndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShiftTemplate_EndDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ShiftTemplate_StartTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShiftTemplate_StartTime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ShiftTemplate_EndTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShiftTemplate_EndTime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''StartDay_DDL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StartDay_DDL As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''EndDay_DDL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EndDay_DDL As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''UpdateShiftTemplate_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdateShiftTemplate_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''CreateShift_SiteNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CreateShift_SiteNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CreateShift_ClientSite_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CreateShift_ClientSite_ID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CreateShift_ClientSite_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CreateShift_ClientSite_Name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CreateShift_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CreateShift_Name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CreateShift_EmployeeDDL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CreateShift_EmployeeDDL As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''CreateShift_Description control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CreateShift_Description As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CreateShift_PayRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CreateShift_PayRate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CreateShift_OnDutyMeals control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CreateShift_OnDutyMeals As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CreateShift_StartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CreateShift_StartDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CreateShift_EndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CreateShift_EndDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CreateShift_StartTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CreateShift_StartTime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CreateShift_EndTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CreateShift_EndTime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CreateShift_StartDay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CreateShift_StartDay As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''CreateShift_EndDay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CreateShift_EndDay As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''HiddenField2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenField2 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''CreateShift_ModalButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CreateShift_ModalButton As Global.System.Web.UI.WebControls.Button
End Class
