'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class adminscheduler

    '''<summary>
    '''Head1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''DisplayingLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DisplayingLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ResourceDDL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ResourceDDL As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''StartDateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StartDateLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''StartDateTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StartDateTB As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DaysLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DaysLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DaysDDL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DaysDDL As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''CellDurationLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CellDurationLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CellDurationDDL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CellDurationDDL As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''CellWidthLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CellWidthLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CellWidthDDL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CellWidthDDL As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''EventHeightLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EventHeightLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EventHeightDDL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EventHeightDDL As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ShowTimesLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShowTimesLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ShowTimes_ImageButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShowTimes_ImageButton As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''EventWidthLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EventWidthLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EventWidthMatters_ImageButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EventWidthMatters_ImageButton As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''DayPilotScheduler control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DayPilotScheduler As Global.DayPilot.Web.Ui.DayPilotScheduler

    '''<summary>
    '''payroll_date_range_start control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents payroll_date_range_start As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hyphen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyphen As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''payroll_date_range_end control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents payroll_date_range_end As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''createMattsFlexFileButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents createMattsFlexFileButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''createExcaliburFlexFileButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents createExcaliburFlexFileButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''PTOButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PTOButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''weekOfDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents weekOfDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RefreshClients_ImageButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RefreshClients_ImageButton As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ClientEyeBall_ImageButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClientEyeBall_ImageButton As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ClientTotalsGridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClientTotalsGridView As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''RefreshEmployees_ImageButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RefreshEmployees_ImageButton As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''EmployeeEyeBall_ImageButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EmployeeEyeBall_ImageButton As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''EmployeeTotalsGridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EmployeeTotalsGridView As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''ReimbursementsGridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReimbursementsGridView As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''SqlDataSource1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource1 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''Reimbursement_AddTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Reimbursement_AddTable As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''linkButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linkButton As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''Reimburse_EmployeeDDL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Reimburse_EmployeeDDL As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Reimburse_DateTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Reimburse_DateTB As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Reimburse_DescriptionTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Reimburse_DescriptionTB As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Reimburse_AmountTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Reimburse_AmountTB As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Reimburse_GrossCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Reimburse_GrossCB As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''RequiredFieldValidator4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator4 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''RequiredFieldValidator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''RequiredFieldValidator2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator2 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''RequiredFieldValidator3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator3 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''SickPayGridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SickPayGridView As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''SqlDataSource2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource2 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SickPay_AddTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SickPay_AddTable As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''linkButton1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linkButton1 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''Sick_EmployeeDDL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Sick_EmployeeDDL As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Sick_DateTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Sick_DateTB As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Sick_DescriptionTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Sick_DescriptionTB As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Sick_MinutesTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Sick_MinutesTB As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RequiredFieldValidator5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator5 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''RequiredFieldValidator7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator7 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''RequiredFieldValidator8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator8 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''RequiredFieldValidator9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator9 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ExcaliburFlexGridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExcaliburFlexGridView As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''MattsFlexGridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MattsFlexGridView As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''PTOGridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PTOGridView As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''ShiftModalLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShiftModalLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ShiftInstance_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShiftInstance_ID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ShiftInstance_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShiftInstance_Name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ShiftInstance_EmployeeDDL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShiftInstance_EmployeeDDL As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ShiftInstance_ShiftNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShiftInstance_ShiftNotes As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ShiftInstance_PayRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShiftInstance_PayRate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ShiftInstance_OnDutyMealPeriods control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShiftInstance_OnDutyMealPeriods As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ShiftInstance_StartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShiftInstance_StartDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ShiftInstance_StartTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShiftInstance_StartTime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ShiftInstance_EndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShiftInstance_EndDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ShiftInstance_EndTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShiftInstance_EndTime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DeleteShift_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DeleteShift_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''UpdateShift_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdateShift_Button As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Shift_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Shift_ID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Client_ID_ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Client_ID_ As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ClientSite_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClientSite_ID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Pre_SI_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pre_SI_Name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Pre_SI_Notes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pre_SI_Notes As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Pre_SI_startdatetime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pre_SI_startdatetime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Pre_SI_enddatetime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pre_SI_enddatetime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Pre_SI_username control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pre_SI_username As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Pre_ST_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pre_ST_Name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Pre_ST_Description control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pre_ST_Description As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Pre_ST_employee_id control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pre_ST_employee_id As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Pre_ST_startdatetime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pre_ST_startdatetime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Pre_ST_enddatetime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pre_ST_enddatetime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Pre_ST_ondutymeals control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pre_ST_ondutymeals As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Pre_ST_startday control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pre_ST_startday As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Pre_ST_endday control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pre_ST_endday As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Pre_ST_username control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pre_ST_username As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ShiftTemplate_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShiftTemplate_Name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ShiftTemplate_EmployeeDDL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShiftTemplate_EmployeeDDL As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ShiftTemplate_ShiftDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShiftTemplate_ShiftDescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ShiftTemplate_PayRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShiftTemplate_PayRate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ShiftTemplate_OnDutyMealPeriods control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShiftTemplate_OnDutyMealPeriods As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ShiftTemplate_StartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShiftTemplate_StartDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ShiftTemplate_EndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShiftTemplate_EndDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ShiftTemplate_StartTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShiftTemplate_StartTime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ShiftTemplate_EndTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShiftTemplate_EndTime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''StartDay_DDL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StartDay_DDL As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''EndDay_DDL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EndDay_DDL As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''UpdateShiftTemplate_Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdateShiftTemplate_Button As Global.System.Web.UI.WebControls.Button
End Class
